/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/meta": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Meta */
        get: operations["meta_api_meta_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Examples */
        get: operations["examples_api_examples_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/examples/{example_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Example Run */
        get: operations["example_run_api_examples__example_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Saved Run
         * @description A finished live run, in the same shape as a cached example so the UI replays it.
         */
        get: operations["saved_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Catalog */
        get: operations["get_catalog_api_catalog_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/credits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Credits
         * @description How much of the live-run spending limit is left; null when there's no limit.
         */
        get: operations["get_credits_api_credits_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Plan */
        post: operations["plan_api_plan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdvertiserProfile */
        AdvertiserProfile: {
            /** Brief */
            brief: string;
            /** Business Summary */
            business_summary: string;
            /** Brand Name */
            brand_name: string | null;
            /**
             * Offering Type
             * @enum {string}
             */
            offering_type: "consumer_product" | "consumer_service" | "b2b" | "unclear";
            product: components["schemas"]["TextAttr"];
            /** Sells */
            sells: string[];
            /** Competes With */
            competes_with: string[];
            /** Interests */
            interests: {
                [key: string]: number;
            };
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Occasions */
            occasions: {
                [key: string]: number;
            };
            /** Positioning */
            positioning: string[];
            price_tier: components["schemas"]["PriceTierAttr"];
            first_order_value_usd: components["schemas"]["NumberAttr"];
            gender: components["schemas"]["GenderAttr"];
            age_range: components["schemas"]["TextAttr"] | null;
            audience: components["schemas"]["TextAttr"] | null;
            business_model: components["schemas"]["BusinessModelAttr"];
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /**
             * Clarity
             * @enum {string}
             */
            clarity: "clear" | "partial" | "unusable";
            /** Clarity Reason */
            clarity_reason: string;
            /** Assumptions */
            assumptions: string[];
            /** Clarifying Questions */
            clarifying_questions: components["schemas"]["ClarifyingQuestion"][];
            /**
             * Dropped Quotes
             * @description Quotes the model gave that aren't in the brief
             */
            dropped_quotes?: string[];
            /**
             * Dropped Tags
             * @description Tags the model gave that aren't in the taxonomy
             */
            dropped_tags?: string[];
        };
        /** Audience */
        Audience: {
            /** Age Skew */
            age_skew: string;
            /** Gender Split */
            gender_split: {
                [key: string]: number;
            };
            /** Top Geos */
            top_geos: string[];
            /**
             * Income Tier
             * @enum {string}
             */
            income_tier: "mid" | "mid-high" | "high";
        };
        /** BidStrategy */
        BidStrategy: {
            /**
             * Type
             * @default target_cpa
             * @constant
             */
            type: "target_cpa";
            /** Target Cpa Usd */
            target_cpa_usd: number;
            /** Max Cpa Usd */
            max_cpa_usd: number;
            /** Allowable Cpa Ratio */
            allowable_cpa_ratio: number;
            /** First Order Value Usd */
            first_order_value_usd: number;
            /**
             * First Order Value Source
             * @enum {string}
             */
            first_order_value_source: "stated" | "inferred" | "assumed";
            /** Learning Period Days */
            learning_period_days: number;
            /** Rationale */
            rationale: string;
        };
        /** Budget */
        Budget: {
            /** Total Usd */
            total_usd: number;
            /** Monthly Usd */
            monthly_usd: number;
            /** Daily Cap Usd */
            daily_cap_usd: number;
            /**
             * Pacing
             * @default even
             * @constant
             */
            pacing: "even";
            /**
             * Currency
             * @default USD
             * @constant
             */
            currency: "USD";
        };
        /** BusinessModelAttr */
        BusinessModelAttr: {
            /**
             * Value
             * @enum {string}
             */
            value: "subscription" | "one_time" | "mixed" | "unknown";
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
            evidence: components["schemas"]["Span"] | null;
            /** Note */
            note: string | null;
        };
        /** CachedRun */
        CachedRun: {
            /** Id */
            id: string;
            /** Brief */
            brief: string;
            /** Events */
            events: (components["schemas"]["StageEvent"] | components["schemas"]["ProfileEvent"] | components["schemas"]["NeedsInputEvent"] | components["schemas"]["PublishersEvent"] | components["schemas"]["PersonasEvent"] | components["schemas"]["CreativeEvent"] | components["schemas"]["ConfigEvent"] | components["schemas"]["DoneEvent"] | components["schemas"]["ErrorEvent"])[];
        };
        /** CampaignConfig */
        CampaignConfig: {
            /**
             * Schema Version
             * @default 1.0
             * @constant
             */
            schema_version: "1.0";
            campaign: components["schemas"]["CampaignMeta"];
            budget: components["schemas"]["Budget"];
            bid_strategy: components["schemas"]["BidStrategy"];
            /** Placements */
            placements: components["schemas"]["Placement"][];
            targeting: components["schemas"]["Targeting"];
            /** Creatives */
            creatives: components["schemas"]["CreativeRef"][];
            frequency_cap: components["schemas"]["FrequencyCap"];
            measurement: components["schemas"]["Measurement"];
            experiment: components["schemas"]["Experiment"];
            review: components["schemas"]["Review"];
        };
        /** CampaignMeta */
        CampaignMeta: {
            /** Name */
            name: string;
            /**
             * Status
             * @default draft
             * @constant
             */
            status: "draft";
            /**
             * Objective
             * @default conversions
             * @constant
             */
            objective: "conversions";
            flight: components["schemas"]["Flight"];
        };
        /** Catalog */
        Catalog: {
            /** Publishers */
            publishers: components["schemas"]["CatalogPublisher"][];
            /** Personas */
            personas: components["schemas"]["CatalogPersona"][];
        };
        /** CatalogPersona */
        CatalogPersona: {
            persona: components["schemas"]["Persona"];
            tags: components["schemas"]["PersonaTags"];
        };
        /**
         * CatalogPublisher
         * @description Publisher row as the API serves it: raw fields plus tags.
         */
        CatalogPublisher: {
            publisher: components["schemas"]["Publisher"];
            tags: components["schemas"]["PublisherTags"];
        };
        /** Claim */
        Claim: {
            /** Claim */
            claim: string;
            evidence: components["schemas"]["Span"];
        };
        /** ClaimUse */
        ClaimUse: {
            /**
             * Claim
             * @description The claim as it appears in the ad
             */
            claim: string;
            /**
             * Source Quote
             * @description The exact brief words that back it
             */
            source_quote: string;
        };
        /** ClarifyingQuestion */
        ClarifyingQuestion: {
            /** Question */
            question: string;
            /**
             * Why
             * @description What would change in the plan with the answer
             */
            why: string;
            /**
             * Suggested Answers
             * @description 2 to 4 short likely answers
             */
            suggested_answers: string[];
        };
        /** ConfigEvent */
        ConfigEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "config";
            config: components["schemas"]["CampaignConfig"];
        };
        /** Creative */
        Creative: {
            /** Creative Id */
            creative_id: string;
            /** Persona Id */
            persona_id: string;
            /** Persona Name */
            persona_name: string;
            /** Angle */
            angle: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Cta */
            cta: string;
            /** Claims Used */
            claims_used: components["schemas"]["ClaimUse"][];
            /** Offer Suggestion */
            offer_suggestion: string | null;
            /** Tone Notes */
            tone_notes: string;
            /**
             * Status
             * @enum {string}
             */
            status: "draft" | "passed" | "revised" | "flagged";
            critique?: components["schemas"]["Critique"] | null;
            revision_of?: components["schemas"]["CreativeDraft"] | null;
        };
        /** CreativeDraft */
        CreativeDraft: {
            /**
             * Angle
             * @description The one idea this variant bets on, in a short phrase
             */
            angle: string;
            /** Headline */
            headline: string;
            /** Body */
            body: string;
            /** Cta */
            cta: string;
            /** Claims Used */
            claims_used: components["schemas"]["ClaimUse"][];
            /**
             * Offer Suggestion
             * @description An optional incentive to test, e.g. 'first box 20% off'. A suggestion for the advertiser, never written into the copy as fact. Empty if none
             */
            offer_suggestion: string;
            /**
             * Tone Notes
             * @description How the copy maps to this persona's preferences
             */
            tone_notes: string;
        };
        /** CreativeEvent */
        CreativeEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "creative";
            creative: components["schemas"]["Creative"];
        };
        /** CreativeRef */
        CreativeRef: {
            /** Creative Id */
            creative_id: string;
            /** Persona Id */
            persona_id: string;
            /** Weight */
            weight: number;
            /** Status */
            status: string;
        };
        /** Credits */
        Credits: {
            /** Limit Usd */
            limit_usd: number;
            /** Spent Usd */
            spent_usd: number;
            /** Remaining Usd */
            remaining_usd: number;
            /** Run Reserve Usd */
            run_reserve_usd: number;
        };
        /** Critique */
        Critique: {
            /** Checks */
            checks: components["schemas"]["RubricCheck"][];
            /** Code Issues */
            code_issues: string[];
            /** Passed */
            passed: boolean;
            /** Fix */
            fix: string | null;
        };
        /** Demographic */
        Demographic: {
            /** Value */
            value: string;
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
        };
        /** DoneEvent */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /** Run Id */
            run_id: string;
            /** Total Ms */
            total_ms: number;
            /** Cost Usd */
            cost_usd: number;
            /** Trace */
            trace: components["schemas"]["StageTrace"][];
        };
        /** ErrorEvent */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Stage */
            stage: string;
            /** Message */
            message: string;
            /**
             * Retryable
             * @default true
             */
            retryable: boolean;
        };
        /** EvidenceRef */
        EvidenceRef: {
            /**
             * Field
             * @enum {string}
             */
            field: "notes" | "category" | "subcategories" | "audience" | "avg_order_value_usd" | "monthly_impressions" | "brief";
            /**
             * Quote
             * @description Exact text of that field (or of the brief) being cited
             */
            quote: string;
        };
        /** Example */
        Example: {
            /** Id */
            id: string;
            /** Brief */
            brief: string;
            /** Cached */
            cached: boolean;
        };
        /** Experiment */
        Experiment: {
            /**
             * Creative Rotation
             * @default even_then_optimize
             * @constant
             */
            creative_rotation: "even_then_optimize";
            /** Test Budget Pct */
            test_budget_pct: number;
            /** Graduate Rule */
            graduate_rule: string;
            /** Notes */
            notes: string;
        };
        /** Flight */
        Flight: {
            /** Start */
            start: string;
            /** End */
            end: string;
            /** Days */
            days: number;
        };
        /** FrequencyCap */
        FrequencyCap: {
            /** Impressions */
            impressions: number;
            /** Per Days */
            per_days: number;
            /** Rationale */
            rationale: string;
        };
        /** GenderAttr */
        GenderAttr: {
            /**
             * Value
             * @enum {string}
             */
            value: "female" | "male" | "any";
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
            evidence: components["schemas"]["Span"] | null;
            /** Note */
            note: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * LaunchSummary
         * @description Written by the LLM from the finished config. Read-only: it never changes a field above,
         *     and any number it states must appear in the config or the brief.
         */
        LaunchSummary: {
            /** Summary */
            summary: string;
            /** Uncertainties */
            uncertainties: string[];
            /** Questions */
            questions: string[];
        };
        /** Measurement */
        Measurement: {
            /**
             * Conversion Event
             * @default purchase
             * @constant
             */
            conversion_event: "purchase";
            /** Attribution Window Days */
            attribution_window_days: number;
            /** Kpis */
            kpis: string[];
            /** Holdout Pct */
            holdout_pct: number;
        };
        /** Meta */
        Meta: {
            /** Models */
            models: components["schemas"]["ModelOption"][];
            /** Default Model */
            default_model: string;
            /** Default Monthly Budget Usd */
            default_monthly_budget_usd: number;
            /** Default Flight Days */
            default_flight_days: number;
            /** Max Brief Chars */
            max_brief_chars: number;
            /** Saved Runs */
            saved_runs: boolean;
        };
        /** ModelOption */
        ModelOption: {
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** NeedsInputEvent */
        NeedsInputEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "needs_input";
            /** Reason */
            reason: string;
            /** Questions */
            questions: components["schemas"]["ClarifyingQuestion"][];
        };
        /** NumberAttr */
        NumberAttr: {
            /** Value */
            value: number;
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
            evidence: components["schemas"]["Span"] | null;
            /** Note */
            note: string | null;
        };
        /** Persona */
        Persona: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Age Range */
            age_range: string;
            /** Gender Skew */
            gender_skew: string;
            /** Description */
            description: string;
            /** Category Affinities */
            category_affinities: string[];
            /** Price Sensitivity */
            price_sensitivity: string;
            /** Messaging Preferences */
            messaging_preferences: string[];
            /** Disinterested In */
            disinterested_in: string[];
            /** Typical Aov Usd */
            typical_aov_usd: number;
        };
        /** PersonaPick */
        PersonaPick: {
            /** Persona Id */
            persona_id: string;
            /** Name */
            name: string;
            /** Score */
            score: number;
            /** Rank */
            rank: number;
            /** Why Plausible */
            why_plausible: string;
            /** Lean Into */
            lean_into: string[];
            /** Avoid */
            avoid: string[];
            /**
             * Ad Angle
             * @default
             */
            ad_angle: string;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Reached Via */
            reached_via: string[];
            /** Conflicts */
            conflicts: string[];
        };
        /** PersonaPlan */
        PersonaPlan: {
            /** Picks */
            picks: components["schemas"]["PersonaPick"][];
            /** Candidates */
            candidates: components["schemas"]["PersonaScore"][];
            /** Skipped Note */
            skipped_note: string | null;
        };
        /** PersonaScore */
        PersonaScore: {
            /** Persona Id */
            persona_id: string;
            /** Score */
            score: number;
            /** Affinity */
            affinity: number;
            /** Values */
            values: number;
            /** Price */
            price: number;
            /** Reach */
            reach: number;
            /** Conflicts */
            conflicts: string[];
            /** Reach Publishers */
            reach_publishers: string[];
            /** Detail */
            detail: string;
        };
        /** PersonaTags */
        PersonaTags: {
            /** Id */
            id: string;
            /** Interests */
            interests: {
                [key: string]: number;
            };
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Occasions */
            occasions: {
                [key: string]: number;
            };
            /** Price Tiers */
            price_tiers: ("value" | "mid" | "premium" | "luxury")[];
            /** Dislikes */
            dislikes: string[];
            /**
             * Enrichment Version
             * @default
             */
            enrichment_version: string;
        };
        /** PersonasEvent */
        PersonasEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "personas";
            plan: components["schemas"]["PersonaPlan"];
        };
        /** Placement */
        Placement: {
            /** Publisher Id */
            publisher_id: string;
            /** Publisher Name */
            publisher_name: string;
            /** Category */
            category: string;
            /**
             * Role
             * @enum {string}
             */
            role: "core" | "test";
            /** Fit Score */
            fit_score: number;
            /** Allocation Pct */
            allocation_pct: number;
            /** Budget Usd */
            budget_usd: number;
            /** Est Conversions */
            est_conversions: number;
            /** Capacity Note */
            capacity_note?: string | null;
            /** Creative Ids */
            creative_ids: string[];
            /** Personas Matched */
            personas_matched: boolean;
            test_plan?: components["schemas"]["TestPlan"] | null;
        };
        /** PlanRequest */
        PlanRequest: {
            /** Brief */
            brief: string;
            /** Monthly Budget Usd */
            monthly_budget_usd?: number | null;
            /** Flight Days */
            flight_days?: number | null;
            /** Model */
            model?: string | null;
            /**
             * Force
             * @description Draft even if the brief is too vague
             * @default false
             */
            force: boolean;
            /**
             * Allow Competitors
             * @description Flag publishers that sell the same products instead of excluding them
             * @default false
             */
            allow_competitors: boolean;
        };
        /** PriceTierAttr */
        PriceTierAttr: {
            /**
             * Value
             * @enum {string}
             */
            value: "value" | "mid" | "premium" | "luxury";
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
            evidence: components["schemas"]["Span"] | null;
            /** Note */
            note: string | null;
        };
        /** ProfileEvent */
        ProfileEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "profile";
            profile: components["schemas"]["AdvertiserProfile"];
        };
        /** Publisher */
        Publisher: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Subcategories */
            subcategories: string[];
            /** Monthly Impressions */
            monthly_impressions: number;
            /** Avg Order Value Usd */
            avg_order_value_usd: number;
            audience: components["schemas"]["Audience"];
            /** Notes */
            notes: string;
        };
        /** PublisherPlan */
        PublisherPlan: {
            /** Summary */
            summary: string;
            /**
             * Explained
             * @description False when the LLM review failed and these are computed scores only
             * @default true
             */
            explained: boolean;
            /** Recommended */
            recommended: components["schemas"]["PublisherResult"][];
            /** Test */
            test: components["schemas"]["PublisherResult"][];
            /** Excluded */
            excluded: components["schemas"]["PublisherResult"][];
            /** Offering Type Doubt */
            offering_type_doubt?: string | null;
        };
        /**
         * PublisherResult
         * @description What the UI shows per publisher: code score + LLM judgment, merged and enforced.
         */
        PublisherResult: {
            /** Publisher Id */
            publisher_id: string;
            /** Name */
            name: string;
            /** Category */
            category: string;
            /** Signals */
            signals: components["schemas"]["Signal"][];
            /** Base Fit */
            base_fit: number;
            /** Fit */
            fit: number;
            /**
             * Computed Tier
             * @enum {string}
             */
            computed_tier: "recommended" | "test" | "excluded";
            /**
             * Tier
             * @enum {string}
             */
            tier: "recommended" | "test" | "excluded";
            /** Tier Reason */
            tier_reason: string | null;
            /** Exclusion Reason */
            exclusion_reason: ("competitor" | "off_category" | "weak_fit" | "review") | null;
            /** Conflict */
            conflict: string | null;
            /** Adjacent Conflict */
            adjacent_conflict: string | null;
            /** Rationale */
            rationale: string;
            /** Evidence */
            evidence: components["schemas"]["EvidenceRef"][];
            /** Risk */
            risk: string | null;
            /** Competitor Dispute */
            competitor_dispute?: string | null;
        };
        /** PublisherTags */
        PublisherTags: {
            /** Id */
            id: string;
            /** Interests */
            interests: {
                [key: string]: number;
            };
            /** Values */
            values: {
                [key: string]: number;
            };
            /** Occasions */
            occasions: {
                [key: string]: number;
            };
            /** Sells */
            sells: string[];
            /**
             * Evidence
             * @default {}
             */
            evidence: {
                [key: string]: string;
            };
            /**
             * Enrichment Version
             * @default
             */
            enrichment_version: string;
        };
        /** PublishersEvent */
        PublishersEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "publishers";
            plan: components["schemas"]["PublisherPlan"];
        };
        /** Review */
        Review: {
            /** Needs Human Review */
            needs_human_review: boolean;
            /**
             * Confidence
             * @enum {string}
             */
            confidence: "high" | "medium" | "low";
            /** Assumptions */
            assumptions: string[];
            /** Warnings */
            warnings: string[];
            launch_summary?: components["schemas"]["LaunchSummary"] | null;
        };
        /** RubricCheck */
        RubricCheck: {
            /**
             * Name
             * @enum {string}
             */
            name: "grounded" | "persona_fit" | "specific" | "placement" | "publisher_safe";
            /** Passed */
            passed: boolean;
            /** Reason */
            reason: string;
        };
        /** Signal */
        Signal: {
            /**
             * Name
             * @enum {string}
             */
            name: "category" | "audience" | "price" | "values" | "reach";
            /** Score */
            score: number;
            /**
             * Neutral
             * @default false
             */
            neutral: boolean;
            /** Detail */
            detail: string;
        };
        /** Span */
        Span: {
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
        };
        /** StageEvent */
        StageEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "stage";
            /**
             * Stage
             * @enum {string}
             */
            stage: "understand" | "publishers" | "personas" | "creative" | "campaign";
            /**
             * Status
             * @enum {string}
             */
            status: "started" | "done" | "failed" | "skipped";
            /** Ms */
            ms?: number | null;
        };
        /** StageTrace */
        StageTrace: {
            /** Stage */
            stage: string;
            /** Name */
            name: string;
            /** Model */
            model?: string | null;
            /** Prompt */
            prompt?: string | null;
            /** Prompt Version */
            prompt_version?: string | null;
            /** Ms */
            ms: number;
            /**
             * Input Tokens
             * @default 0
             */
            input_tokens: number;
            /**
             * Output Tokens
             * @default 0
             */
            output_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /**
             * Retries
             * @default 0
             */
            retries: number;
            /**
             * Ok
             * @default true
             */
            ok: boolean;
            /** Error */
            error?: string | null;
        };
        /** Targeting */
        Targeting: {
            /** Personas */
            personas: string[];
            gender: components["schemas"]["Demographic"] | null;
            age_range: components["schemas"]["Demographic"] | null;
            /** Geo */
            geo: string[];
            /** Contextual Interests */
            contextual_interests: string[];
            /** Exclusions */
            exclusions: string[];
        };
        /**
         * TestPlan
         * @description What a test placement is for, and the rule that ends the test.
         */
        TestPlan: {
            /** Hypothesis */
            hypothesis: string;
            /** Risk */
            risk: string | null;
            /** Promote If */
            promote_if: string;
            /** Cut If */
            cut_if: string;
        };
        /** TextAttr */
        TextAttr: {
            /** Value */
            value: string;
            /**
             * Source
             * @enum {string}
             */
            source: "stated" | "inferred" | "assumed";
            evidence: components["schemas"]["Span"] | null;
            /** Note */
            note: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    meta_api_meta_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meta"];
                };
            };
        };
    };
    examples_api_examples_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Example"][];
                };
            };
        };
    };
    example_run_api_examples__example_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                example_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    saved_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CachedRun"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_catalog_api_catalog_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Catalog"];
                };
            };
        };
    };
    get_credits_api_credits_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Credits"] | null;
                };
            };
        };
    };
    plan_api_plan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
